# Generated by Django 2.2.12 on 2020-05-03 22:26

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=250)),
                ('name', models.CharField(default=apps.files.models._generate, max_length=32)),
                ('file', models.FileField(upload_to='files')),
                ('ttl', models.SmallIntegerField(default=300)),
                ('comment', models.CharField(max_length=250)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=128)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
